---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - synk.io
  resources:
  - synksources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synk.io
  resources:
  - synksources/finalizers
  verbs:
  - update
- apiGroups:
  - synk.io
  resources:
  - synksources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - synk.io
  resources:
  - synktargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synk.io
  resources:
  - synktargets/finalizers
  verbs:
  - update
- apiGroups:
  - synk.io
  resources:
  - synktargets/status
  verbs:
  - get
  - patch
  - update
