# permissions for end users to edit synksources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: synksource-editor-role
rules:
- apiGroups:
  - synk.io
  resources:
  - synksources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synk.io
  resources:
  - synksources/status
  verbs:
  - get
